name: Build Docker Image

on: [push]

defaults:
  run:
    working-directory: build

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: build

      - name: Build
        uses: php-actions/composer@v6
        with:
          php_version: "8.1"
          dev: no
          args: --optimize-autoloader
          working_dir: build

      - name: Display structure of files
        run: ls -R

      - name: Cleanup
        run: |
          sudo rm -rf var/cache/*

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: backend
          path: build

  build-image:
    needs: build-backend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/wamp'
    steps:
      - name: Download Backend artifacts
        uses: actions/download-artifact@v3
        with:
          name: backend
          path: ./

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
